$NetBSD: patch-Cargo.toml,v 1.4 2023/02/03 21:28:37 pin Exp $

Don't pull from a specific pull-request.
Patch tree_magic_mini crate within pkgsrc.

--- Cargo.toml.orig	2023-02-03 06:22:23.000000000 +0000
+++ Cargo.toml
@@ -49,7 +49,7 @@ const_format = "0.2.22"
 owo-colors = "3.3.0"
 wu-diff = "0.1.2"
 rayon = "1.6.1"
-tree_magic_mini = "3.0.2"
+tree_magic_mini = "3.0.3"
 bumpalo = "3.11.1"
 unicode-width = "0.1.9"
 crossterm = { version = "0.25.0", features = [] }
@@ -68,9 +68,3 @@ lto = "thin"
 [[bin]]
 name = "difft"
 path = "src/main.rs"
-
-[features]
-
-[patch.crates-io]
-# https://github.com/mbrubeck/tree_magic/pull/13 hasn't been merged yet.
-tree_magic_mini = { git = 'https://github.com/Wilfred/tree_magic', branch = 'fix-panic-for-empty-strings' }
