$NetBSD: patch-Cargo.toml,v 1.7 2023/08/17 02:43:21 pin Exp $

Don't pull from a specific pull-request.
Patch tree_magic_mini crate within pkgsrc.

--- Cargo.toml.orig	2023-08-16 06:01:09.000000000 +0000
+++ Cargo.toml
@@ -54,7 +54,7 @@ const_format = "0.2.22"
 owo-colors = "3.5.0"
 wu-diff = "0.1.2"
 rayon = "1.7.0"
-tree_magic_mini = "3.0.2"
+tree_magic_mini = "3.0.3"
 # bumpalo 3.12 requires rust 1.60
 bumpalo = "3.11.1"
 unicode-width = "0.1.9"
@@ -84,9 +84,3 @@ lto = "thin"
 [[bin]]
 name = "difft"
 path = "src/main.rs"
-
-[features]
-
-[patch.crates-io]
-# https://github.com/mbrubeck/tree_magic/pull/13 hasn't been merged yet.
-tree_magic_mini = { git = 'https://github.com/Wilfred/tree_magic', branch = 'fix-panic-for-empty-strings' }
