$NetBSD: patch-Cargo.toml,v 1.1 2023/04/27 18:16:41 pin Exp $

Bump git2

--- Cargo.toml.orig	2023-04-26 18:52:59.000000000 +0000
+++ Cargo.toml
@@ -29,7 +29,7 @@ gix-features-for-configuration-only = { 
 gix = { version = "0.44.0", default-features = false, features = [
     "max-performance-safe",
 ] }
-git2 = { version = "0.16.1", default-features = false }
+git2 = { version = "0.17.1", default-features = false }
 human-panic = "1.1.0"
 image = "0.24.6"
 num-format = "0.4.4"
