$NetBSD: patch-four-bar-ui_Cargo.toml,v 1.1 2024/06/01 14:17:49 pin Exp $

Don't pull git version of ron.

--- four-bar-ui/Cargo.toml.orig	2024-06-01 13:38:57.716816987 +0000
+++ four-bar-ui/Cargo.toml
@@ -26,7 +26,7 @@ smartcore = { version = "0.3", features 
 serde = { version = "1", features = ["derive"] }
 egui_plot = "0.27"
 rfd = "0.14"
-ron = { git = "https://github.com/ron-rs/ron" }
+ron = "0.8"
 
 [dependencies.four-bar]
 version = "7"
