$NetBSD: patch-Cargo.toml,v 1.1 2023/06/04 20:18:34 pin Exp $

Fix for libgit2

--- Cargo.toml.orig	2023-06-03 14:04:09.000000000 +0000
+++ Cargo.toml
@@ -46,7 +46,7 @@ vte = "0.11.0"
 xdg = "2.4.1"
 
 [dependencies.git2]
-version = "0.16.1"
+version = "0.17.2"
 default-features = false
 features = []
 
