$NetBSD: patch-Cargo.toml,v 1.1 2023/04/28 18:56:22 maya Exp $

Enable patching authenticator-rs

--- Cargo.toml.orig	2023-04-14 16:27:55.000000000 +0000
+++ Cargo.toml
@@ -188,3 +188,6 @@ uniffi_bindgen = "=0.23.0"
 uniffi_build = "=0.23.0"
 uniffi_macros = "=0.23.0"
 weedle2 = "=4.0.0"
+
+[patch.crates-io.authenticator]
+path = "third_party/rust/authenticator"
