$NetBSD: patch-pyproject.toml,v 1.2 2023/05/05 09:56:30 wiz Exp $

Switch to pdm-backend
https://github.com/regen100/cmake-language-server/issues/76

--- pyproject.toml.orig	2023-03-09 10:01:30.924441300 +0000
+++ pyproject.toml
@@ -38,9 +38,9 @@ cmake-language-server = "cmake_language_
 
 [build-system]
 requires = [
-    "pdm-pep517>=1.0.0",
+    "pdm-backend>=1.0.0",
 ]
-build-backend = "pdm.pep517.api"
+build-backend = "pdm.backend"
 
 [tool.pdm.version]
 source = "scm"
