$NetBSD: patch-pyproject.toml,v 1.3 2023/10/23 11:09:04 adam Exp $

Allow Python 3.12

--- pyproject.toml.orig	2023-10-17 14:00:48.524893800 +0000
+++ pyproject.toml
@@ -8,7 +8,7 @@ authors = [
 dependencies = [
     "pygls>=1.1.1",
 ]
-requires-python = ">=3.7.9,<3.12"
+requires-python = ">=3.7.9,<3.13"
 readme = "README.md"
 keywords = [
     "cmake",
