$NetBSD: patch-git-cliff-core_Cargo.toml,v 1.3 2023/08/31 12:59:53 pin Exp $

Fix libgit2 mismatch

--- git-cliff-core/Cargo.toml.orig	2023-08-31 08:01:43.000000000 +0000
+++ git-cliff-core/Cargo.toml
@@ -28,7 +28,7 @@ toml = "0.7.6"
 lazy-regex = "3.0.1"
 
 [dependencies.git2]
-version = "0.18.0"
+version = "0.17.1"
 default-features = false
 optional = true
 
