$NetBSD: patch-git-cliff-core_Cargo.toml,v 1.4 2023/10/01 09:59:17 pin Exp $

Fix libgit2 mismatch.

--- git-cliff-core/Cargo.toml.orig	2023-09-30 14:03:47.000000000 +0000
+++ git-cliff-core/Cargo.toml
@@ -28,7 +28,7 @@ toml = "0.8.1"
 lazy-regex = "3.0.2"
 
 [dependencies.git2]
-version = "0.18.1"
+version = "0.17.1"
 default-features = false
 optional = true
 
