$NetBSD: patch-git-cliff-core_Cargo.toml,v 1.1 2023/04/27 12:32:36 pin Exp $

Fix build with latest libgit2

--- git-cliff-core/Cargo.toml.orig	2023-01-20 12:31:43.000000000 +0000
+++ git-cliff-core/Cargo.toml
@@ -23,7 +23,7 @@ toml = "0.5.11"
 lazy-regex = "2.4.1"
 
 [dependencies.git2]
-version = "0.16.0"
+version = "0.17.1"
 default-features = false
 
 [dependencies.config]
