$NetBSD: patch-Cargo.toml,v 1.2 2023/10/20 07:05:38 pin Exp $

Switch to newer libgit2-sys.

--- Cargo.toml.orig	2023-03-25 09:31:31.000000000 +0000
+++ Cargo.toml
@@ -68,7 +68,7 @@ walkdir = { version = "2.0", optional = 
 bytesize = { version = "1.1.0" }
 
 [dependencies.git2]
-version = "0.16"
+version = "0.18"
 optional = true
 default-features = false
 
