$NetBSD: patch-pyproject.toml,v 1.1 2023/10/24 14:52:36 adam Exp $

Don't install extra file into site-packages.

--- pyproject.toml.orig	2023-10-24 14:47:07.210900404 +0000
+++ pyproject.toml
@@ -32,11 +32,6 @@ keywords=["pylint", "django", "plugin"]
 packages = [
   { include = "pylint_django/"}
 ]
-include = [
-  "LICENSE",
-  "*.rst",
-  "*.md"
-]
 exclude = ["**/tests/**", "**/testutils.py", "**/tests.py"]
 
 [tool.poetry.dependencies]
