$NetBSD: patch-pyproject.toml,v 1.1 2024/04/26 20:10:47 adam Exp $

Do not install additional files into site-packages directory.
https://github.com/rspeer/python-ftfy/issues/208

--- pyproject.toml.orig	2024-04-26 20:03:26.188129942 +0000
+++ pyproject.toml
@@ -4,7 +4,6 @@ version = "6.2.0"
 description = "Fixes mojibake and other problems with Unicode, after the fact"
 authors = ["Robyn Speer <rspeer@arborelia.net>"]
 license = "Apache-2.0"
-include = ["README.md", "CHANGELOG.md", "tests"]
 readme = "README.md"
 
 [tool.poetry.dependencies]
