$NetBSD: patch-crates_nu-command_Cargo.toml,v 1.3 2023/12/18 06:44:40 pin Exp $

Don't use procfs on NetBSD.

--- crates/nu-command/Cargo.toml.orig	2023-12-17 20:20:27.103974635 +0000
+++ crates/nu-command/Cargo.toml
@@ -106,7 +106,7 @@ libc = "0.2"
 umask = "2.1"
 nix = { version = "0.27", default-features = false, features = ["user"] }
 
-[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "android"), not(target_os = "ios")))'.dependencies]
+[target.'cfg(all(unix, not(target_os = "macos"), not(target_os = "android"), not(target_os = "ios"), not(target_os = "netbsd")))'.dependencies]
 procfs = "0.16.0"
 
 [target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies.trash]
