$NetBSD: patch-Cargo.toml,v 1.1 2023/10/22 19:40:04 pin Exp $

Use serde derive feature.

--- Cargo.toml.orig	2023-10-21 20:23:38.000000000 +0000
+++ Cargo.toml
@@ -41,7 +41,7 @@ rand = "0.8.3"
 regex = { version = "1", default-features = false, features = ["std"] }
 roff = { version = "0.2.1", optional = true }
 rpassword = "5.0.0"
-serde = "1.0"
+serde = { version = "1.0", features = ["derive"] }
 serde_json = { version = "1.0", features = ["preserve_order"] }
 serde_urlencoded = "0.7.0"
 termcolor = "1.1.2"
