$NetBSD: patch-tests_Cargo.toml,v 1.5 2023/08/17 02:49:19 pin Exp $

Patch out the git source request for iai.

--- tests/Cargo.toml.orig	2023-08-07 15:19:41.000000000 +0000
+++ tests/Cargo.toml
@@ -10,7 +10,7 @@ publish = false
 typst = { path = "../crates/typst" }
 typst-library = { path = "../crates/typst-library" }
 comemo = "0.3"
-iai = { git = "https://github.com/reknih/iai" }
+iai = "0.1.1"
 once_cell = "1"
 oxipng = { version = "8.0.0", default-features = false, features = ["filetime", "parallel", "zopfli"] }
 rayon = "1.7.0"
