$NetBSD: patch-crates_typst-cli_Cargo.toml,v 1.2 2023/11/05 08:38:39 pin Exp $

Patch out the git source request for self-update.

--- crates/typst-cli/Cargo.toml.orig	2023-10-31 00:36:21.000000000 +0000
+++ crates/typst-cli/Cargo.toml
@@ -38,7 +38,7 @@ open = "5"
 pathdiff = "0.2"
 same-file = "1"
 # https://github.com/mitsuhiko/self-replace/pull/16
-self-replace = { git = "https://github.com/typst/self-replace", optional = true }
+self-replace = { version = "1.3.5", optional = true }
 semver = "1"
 serde = "1.0.184"
 serde_json = "1"
