$NetBSD: patch-plugin_Cargo.toml,v 1.1 2023/10/22 19:42:05 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2.

--- plugin/Cargo.toml.orig	2023-10-21 05:27:26.000000000 +0000
+++ plugin/Cargo.toml
@@ -11,7 +11,7 @@ shared = { path = "../shared" }
 # External dependencies
 ansi-to-tui   = "^3"
 anyhow        = "^1"
-mlua          = { version = "^0", features = [ "luajit52", "vendored", "serialize" ] }
+mlua          = { version = "^0", features = [ "luajit52", "serialize" ] }
 ratatui       = "^0"
 tracing       = "^0"
 unicode-width = "^0"
