$NetBSD: patch-pyproject.toml,v 1.1 2023/05/04 06:59:57 adam Exp $

pdm-pep517 as been renamed and re-published as pdm-backend.

--- pyproject.toml.orig	2023-05-04 05:25:01.000000000 +0000
+++ pyproject.toml
@@ -1,8 +1,8 @@
 [build-system]
 requires = [
-    "pdm-pep517",
+    "pdm-backend",
 ]
-build-backend = "pdm.pep517.api"
+build-backend = "pdm.backend"
 
 [project]
 name = "unearth"
