$NetBSD: patch-pyproject.toml,v 1.6 2023/06/25 22:54:34 js Exp $

Patch out cryptography check: It doesn't need a version this high and it was
added by upstream as an ugly hack to force a patched OpenSSL, in case it is
linked statically.

--- pyproject.toml.orig	2023-02-28 16:57:09.000000000 +0000
+++ pyproject.toml
@@ -199,7 +197,7 @@ bleach = ">=1.4.3"
 typing-extensions = ">=3.10.0.1"
 # We enforce that we have a `cryptography` version that bundles an `openssl`
 # with the latest security patches.
-cryptography = ">=3.4.7"
+cryptography = ">=3.3.2"
 # ijson 3.1.4 fixes a bug with "." in property names
 ijson = ">=3.1.4"
 matrix-common = "^1.3.0"
