$NetBSD: patch-pyproject.toml,v 1.1 2024/12/09 08:13:21 wiz Exp $

Remove unused dependencies.
https://github.com/pypa/pip-audit/issues/862

--- pyproject.toml.orig	2024-12-09 08:12:10.647544090 +0000
+++ pyproject.toml
@@ -29,7 +29,6 @@ classifiers = [
 dependencies = [
     "CacheControl[filecache] >= 0.13.0",
     "cyclonedx-python-lib >= 5,< 8",
-    "html5lib>=1.1",
     "packaging>=23.0.0",                 # https://github.com/pypa/pip-audit/issues/464
     "pip-api>=0.0.28",
     "pip-requirements-parser>=32.0.0",
@@ -55,7 +54,6 @@ lint = [
     "setuptools",
     "interrogate",
     "mypy",
-    "types-html5lib",
     "types-requests",
     "types-toml",
 ]
