$NetBSD: patch-Cargo.toml,v 1.1 2021/03/24 14:09:33 pin Exp $

Don't use the git version of libmacchina

--- Cargo.toml.orig	2021-03-23 09:37:44.000000000 +0000
+++ Cargo.toml
@@ -17,7 +17,7 @@ codegen-units = 1
 
 [dependencies]
 num_cpus = "1.13.0"
-libmacchina = { git = "https://github.com/Macchina-CLI/libmacchina", branch = "main", version = "0.1.3" }
+libmacchina = "0.1.3"
 bytesize = "1.0.1"
 clap = "2.33.3"
 tui = { version = "0.14.0", default-features = false, features = ['crossterm'] }
