$NetBSD: patch-Cargo.toml,v 1.2 2021/04/06 07:18:56 pin Exp $

Use the crates.io version of libmacchina

--- Cargo.toml.orig	2021-04-05 20:55:03.000000000 +0000
+++ Cargo.toml
@@ -17,7 +17,7 @@ codegen-units = 1
 
 [dependencies]
 num_cpus = "1.13.0"
-libmacchina = { git = "https://github.com/Macchina-CLI/libmacchina", branch = "main", version = "0.1.7" }
+libmacchina = "0.1.7"
 bytesize = "1.0.1"
 clap = "2.33.3"
 tui = { version = "0.14.0", default-features = false, features = ['crossterm'] }
