$NetBSD: patch-Cargo.toml,v 1.4 2022/01/01 22:30:27 pin Exp $

Provide unpublished crate

--- Cargo.toml.orig	2022-01-01 14:37:43.000000000 +0000
+++ Cargo.toml
@@ -25,7 +25,7 @@ clap_complete = "3"
 strum = { version = "0.23", features = ["derive"] }
 exitcode = "1.1"
 anyhow = "1.0"
-prettytable-rs = "0.8"
+prettytable-rs = { path = "prettytable-rs-3239b51dbbb449e69cd599b83bfb152441209cc3" }
 
 [build-dependencies]
 clap = { version = "3", features = ["wrap_help", "derive"] }
@@ -35,6 +35,3 @@ strum = { version = "0.23", features = [
 [profile.release]
 lto = true
 codegen-units = 1
-
-[patch.crates-io]
-prettytable-rs = { git = "https://github.com/wfxr/prettytable-rs" }
