$NetBSD: patch-Cargo.toml,v 1.8 2022/01/02 16:30:06 pin Exp $

Don't force ncurses backend

--- Cargo.toml.orig	2022-01-01 20:46:53.000000000 +0000
+++ Cargo.toml
@@ -45,7 +45,6 @@ strum_macros = "0.23.1"
 regex = "1"
 ioctl-rs = { version = "0.2", optional = true }
 serde_cbor = "0.11.2"
-pancurses = { version = "0.17.0", features = ["win32"], optional = true }
 libc = "0.2.111"
 parse_duration = "2.1.1"
 
