$NetBSD: patch-src___bcrypt_Cargo.toml,v 1.1 2024/05/03 19:19:20 he Exp $

Try to use a newer version of pyo3, ref.
https://github.com/PyO3/pyo3/issues/4153

--- src/_bcrypt/Cargo.toml.orig	2023-12-15 14:39:10.000000000 +0000
+++ src/_bcrypt/Cargo.toml
@@ -6,7 +6,7 @@ edition = "2018"
 publish = false
 
 [dependencies]
-pyo3 = { version = "0.20.0", features = ["abi3"] }
+pyo3 = { version = "0.20.3", features = ["abi3"] }
 bcrypt = "0.15"
 bcrypt-pbkdf = "0.10.0"
 base64 = "0.21.5"
