$NetBSD: patch-Cargo.toml,v 1.27 2024/01/04 12:29:34 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2.

--- Cargo.toml.orig	2024-01-04 11:49:28.353957218 +0000
+++ Cargo.toml
@@ -73,7 +73,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.9.2"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.8.0"
