$NetBSD: patch-Cargo.toml,v 1.1 2021/04/11 18:55:25 pin Exp $

Do not use git-version crates

--- Cargo.toml.orig	2021-04-11 16:52:36.000000000 +0000
+++ Cargo.toml
@@ -27,7 +27,7 @@ lazy_static = "1.4.0"
 
 [dev-dependencies]
 criterion = "0.3"
-cucumber_rust = { git = "https://github.com/bbqsrc/cucumber-rust", branch = "main" }
+cucumber_rust = "0.8.4"
 tokio = { version = "1.4.0", features = ["full"] }
 
 [[bench]]
