$NetBSD: patch-Cargo.toml,v 1.15 2022/04/14 10:59:06 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2

--- Cargo.toml.orig	2022-04-14 08:23:20.000000000 +0000
+++ Cargo.toml
@@ -58,7 +58,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.7.4"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.1.2"
