$NetBSD: patch-Cargo.toml,v 1.26 2023/08/08 20:01:44 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2.

--- Cargo.toml.orig	2023-08-07 18:17:41.000000000 +0000
+++ Cargo.toml
@@ -73,7 +73,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.8.9"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.8.0"
