$NetBSD: patch-Cargo.toml,v 1.25 2023/05/22 12:51:35 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2.

--- Cargo.toml.orig	2023-05-22 04:45:42.000000000 +0000
+++ Cargo.toml
@@ -72,7 +72,7 @@ features = ['serde']
 
 [dependencies.mlua]
 version = "0.8.9"
-features = ['luajit', 'vendored', 'serialize', 'send']
+features = ['luajit', 'serialize', 'send']
 
 [dependencies.tui-input]
 version = "0.7.0"
