$NetBSD: patch-Cargo.toml,v 1.10 2021/11/10 08:44:55 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2

--- Cargo.toml.orig	2021-11-10 04:54:59.000000000 +0000
+++ Cargo.toml
@@ -31,7 +31,7 @@ lazy_static = "1.4.0"
 indexmap = { version = "1.7.0", features = ["serde"] }
 natord = "1.0.9"
 humansize = "1.1.1"
-mlua = { version = "0.6.6", features = ["luajit", "vendored", "serialize", "send"] }
+mlua = { version = "0.6.6", features = ["luajit", "serialize", "send"] }
 ansi-to-tui = "0.4.1"
 libc = "0.2.106"
 tui-input = { version = "0.1.2", features = [ "serde" ] }
