$NetBSD: patch-Cargo.toml,v 1.1 2024/12/02 20:26:21 adam Exp $

Fix build for Rust 1.80.0 and newer.
https://github.com/kbknapp/cargo-outdated/pull/403

--- Cargo.toml.orig	2024-02-26 16:23:06.000000000 +0000
+++ Cargo.toml
@@ -20,16 +20,16 @@ license = "MIT"
 readme = "README.md"
 repository = "https://github.com/kbknapp/cargo-outdated.git"
 description = "Cargo subcommand for displaying when dependencies are out of date"
-rust-version = "1.73.0" # MSRV
+rust-version = "1.81.0" # MSRV
 
 [[bin]]
 name = "cargo-outdated"
 
 [dependencies]
 anyhow = "1.0"
-cargo = "0.76.0"
-env_logger = "0.10.0"
-git2-curl = "0.19.0"
+cargo = "0.84.0"
+env_logger = "0.11.5"
+git2-curl = "0.20.0"
 semver = "1.0.0"
 serde = {version="1.0.114", features = ["derive"]}
 serde_json = "1.0.56"
@@ -37,7 +37,7 @@ tabwriter = "1.2.1"
 tempfile = "3.6"
 toml = "0.8.6"
 clap = { version = "4.1.4", features = ["derive"] }
-strum = { version = "0.25.0", features = ["derive"] }
+strum = { version = "0.26.3", features = ["derive"] }
 
 [features]
 debug = []
