$NetBSD: patch-pyproject.toml,v 1.1 2023/05/04 09:38:36 wiz Exp $

Convert to pdm-pep517 replacement, pdm-backend.
https://github.com/bagel897/pytoolconfig/issues/14

--- pyproject.toml.orig	2023-01-04 21:38:24.718939300 +0000
+++ pyproject.toml
@@ -15,7 +15,7 @@ authors = [
 version = "1.2.5"
 
 [project.license]
-file = "LGPL-3.0"
+file = "LICENSE"
 
 [project.urls]
 Homepage = "https://github.com/bageljrkhanofemus/pytoolconfig"
@@ -75,6 +75,6 @@ strict = true
 
 [build-system]
 requires = [
-    "pdm-pep517>=1.0.5",
+    "pdm-backend>=1.0.5",
 ]
-build-backend = "pdm.pep517.api"
+build-backend = "pdm.backend"
