$NetBSD: patch-git-branchless-invoke_Cargo.toml,v 1.1 2023/04/26 11:36:25 wiz Exp $

Switch to newer libgit2-sys that's compatible with libgit2-1.6.4.

--- git-branchless-invoke/Cargo.toml.orig	2023-03-17 17:20:34.000000000 +0000
+++ git-branchless-invoke/Cargo.toml
@@ -14,7 +14,7 @@ color-eyre = "0.6.2"
 cursive_core = "0.3.6"
 eyre = "0.6.8"
 git-branchless-opts = { version = "0.7.1", path = "../git-branchless-opts" }
-git2 = { version = "0.16.1", default-features = false }
+git2 = { version = "0.17.1", default-features = false }
 lib = { package = "git-branchless-lib", version = "0.7.1", path = "../git-branchless-lib" }
 tracing = "0.1.37"
 tracing-chrome = "0.6.0"
