$NetBSD: patch-git-branchless-lib_Cargo.toml,v 1.1 2023/04/26 11:36:25 wiz Exp $

Switch to newer libgit2-sys that's compatible with libgit2-1.6.4.

--- git-branchless-lib/Cargo.toml.orig	2023-03-17 17:20:34.000000000 +0000
+++ git-branchless-lib/Cargo.toml
@@ -56,7 +56,7 @@ eden_dag = { package = "esl01-dag", vers
 eyre = "0.6.8"
 futures = "0.3.27"
 git-record = { version = "0.3", path = "../git-record" }
-git2 = { version = "0.16.1", default-features = false }
+git2 = { version = "0.17.1", default-features = false }
 indicatif = { version = "0.17.3", features = ["improved_unicode"] }
 itertools = "0.10.3"
 lazy_static = "1.4.0"
