$NetBSD: patch-meli_Cargo.toml,v 1.2 2024/11/28 08:46:12 pin Exp $

Avoid static linking of vendored libraries.

--- meli/Cargo.toml.orig	2024-11-27 21:55:37.478773090 +0000
+++ meli/Cargo.toml
@@ -50,7 +50,7 @@ toml = { version = "0.8", default-featur
 xdg = { version = "2.1.0" }
 
 [features]
-default = ["sqlite3", "notmuch", "smtp", "dbus-notifications", "gpgme", "cli-docs", "jmap", "static"]
+default = ["sqlite3", "notmuch", "smtp", "dbus-notifications", "gpgme", "cli-docs", "jmap"]
 notmuch = ["melib/notmuch"]
 jmap = ["melib/jmap"]
 sqlite3 = ["melib/sqlite3"]
@@ -66,7 +66,7 @@ http-static = ["melib/http-static"]
 sqlite3-static = ["melib/sqlite3-static"]
 dbus-static = ["dep:notify-rust", "notify-rust?/d_vendored"]
 libz-static = ["dep:libz-sys", "libz-sys?/static"]
-static = ["tls-static", "http-static", "sqlite3-static", "dbus-static", "libz-static"]
+#static = ["tls-static", "http-static", "sqlite3-static", "dbus-static", "libz-static"]
 
 # Print tracing logs as meli runs in stderr
 # enable for debug tracing logs: build with --features=debug-tracing and export MELI_DEBUG_STDERR
