$NetBSD: patch-Cargo.toml,v 1.8 2023/02/01 20:39:42 pin Exp $

Don't pull from git, patch vendor crate instead.

--- Cargo.toml.orig	2023-01-31 20:04:04.000000000 +0000
+++ Cargo.toml
@@ -27,7 +27,7 @@ log = "0.4.16"
 simplelog = "0.12.0"
 content_inspector = "0.2.4"
 crossterm = "0.25.0"
-syntect = {version = "5.0.0", git = "https://github.com/kyoheiu/syntect"}
+syntect = "5.0.0"
 serde_yaml = "0.9.14"
 zip = "0.6.3"
 tar = "0.4.38"
