$NetBSD: patch-Cargo.toml,v 1.1 2022/04/03 09:17:56 wiz Exp $

rust-1.58 compat.

--- Cargo.toml.orig	2022-03-30 01:16:04.000000000 +0000
+++ Cargo.toml
@@ -17,7 +17,6 @@ test = false
 bench = false
 
 [profile.release]
-strip = true
 
 [dependencies]
 chrono = "0.4.19"
