$NetBSD: patch-environment.yml,v 1.1 2023/07/20 14:46:43 bacon Exp $

# Hack to allow apps to run despite known issues

--- environment.yml.orig	2023-07-20 13:09:50.054239819 +0000
+++ environment.yml
@@ -19,7 +19,7 @@ dependencies:
   - pillow>=6.2
   - pybind11>=2.6.0
   - pygobject
-  - pyparsing!=3.1.0
+  - pyparsing>=2.3.1
   - pyqt
   - python-dateutil>=2.1
   - setuptools
